### ISSUE TITLE
Does not compile due to duplicate player.pas unit

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#1]
Hey there,

Long time no c man, how's stuff going in these icky times?

On point now: You have 1 `player.pas` and 1 `player\player.pas` untis.

I suppose the compiler searches for the current dir first and then for any other.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Chris,

Per 987e4ce it compiles again. But I still think you should clean up the `player.pas` file outside the `/player` folder.

Cheers,
Gus

**Comment by cyberfilth** [comment]
Hi Gus,

Good to hear from you again. Good catch too, thanks for that. I've removed the duplicate player unit now.

**Comment by gcarreno** [comment]
Hey Chris,

Cool, cool, thanks man!!

Cheers,
Gus
