### ISSUE TITLE
Game states I'm dead, twice, with 9 HP

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#11]
Hey Chris,

![cyberfilth-axe-you-are-dead-twice](https://user-images.githubusercontent.com/81799/80833123-d9702b00-8be5-11ea-8f1a-dee269c5e48f.png)

As you can see from the image, the game stated that I was dead. That was the second time. The other is already out of the screen.

Dunno how to give you any more help than this, sorry.

I really need to dive into your code!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Chris,

After discovering the map on the right upper corner, the game crashed.

Linking the saved game...

[axes.data.txt](https://github.com/cyberfilth/Axes-Armour-Ale/files/4565941/axes.data.txt)

Cheers,
Gus

**Comment by cyberfilth** [comment]
Hmm, from looking at the save file (thanks for including that, it's a big help) your health was actually -12 at the time. It looks like I'm not calling the UpdateHealth function in the UI enough. I'll take a look at that.

As for the game crashing, I think that's a 'range out of bounds error' that crops up intermittently. I _think_ that it's caused by a glitchy FoV that extends outside the edge of the map. I'll take a look at that too.
Thanks for checking it out!

**Comment by gcarreno** [comment]
Hey Chris,

No probs, you're quite welcome.

> ... looking at the save file (thanks for including that, it's a big help) ...

Yeah, a habit I picked up from testing [The Colonists](https://thecolonistsgame.com/)

> Thanks for checking it out!

Every time you commit stuff I take peek, no problem at all :)

BTW, I must apologise I haven't started the tests. I was a bit obsessed with the `setup-lazarus` Action that I forgot about everything else. I know have it at a point that I only need to muster courage to deal with macOS and the dreaded `*.dmg`.

Also, you not using OOP kinda makes it a rather interesting challenge I haven't had the courage to tackle, to be honest, ehehehe.

But I will !!!

Cheers,
Gus

**Comment by cyberfilth** [comment]
Yeah, I've just come off a year of using Java where **everything** is an object and wanted to test myself to see if I could use advanced records instead. It's kinda simple keeping everything on the stack.

No problems with the testing, it's given me a little more time to do some refactoring anyway ;-)

**Comment by gcarreno** [comment]
Hey Chris,

> ... see if I could use advanced records instead ...

Yeah, that's something I'll have to deeply look into. For me a record with methods is quite odd, since that's, KINDA, how I see what objects are...

> No problems with the testing, it's given me a little more time to do some refactoring anyway ;-)

Yeah, I was banking on that. Hence me not being terribly ashamed of not having the tests started, ehehe

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Chris

I'm closing this issue since I think you nipped in the butt with da4efed.

Cheers,
Gus
