### ISSUE TITLE
I am Invincible!!

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#15]
Hey Chris,

I'll let the images talk...
( Attaching a save file: [axe.data.txt](https://github.com/cyberfilth/Axes-Armour-Ale/files/4583164/axe.data.txt) )

![cyberfilth-can-live-with-minus-health](https://user-images.githubusercontent.com/81799/81106762-0c7c2c80-8f0e-11ea-9ec6-2eb169c14be0.png)

![cyberfilth-new-message](https://user-images.githubusercontent.com/81799/81106823-2158c000-8f0e-11ea-8f7a-4a1f5ab5ec69.png)

![cyberfilth-i-am-invinceable](https://user-images.githubusercontent.com/81799/81106846-29b0fb00-8f0e-11ea-8058-4dbc85dadfe6.png)

**Comment by cyberfilth** [comment]
Yup, at the moment you can keep playing after your health drops to zero.
The log message 'You are dead' is the only indication that the game has noticed. I need to add a 'Win' and a 'Lose' screen at some point, but for now enjoy the invincibility!

I'll leave this issue open as a reminder to add the game over game state, I think that my to-do list currently involves.

- ~~Adding armour items~~
- ~~Adding 'game over' game state~~
- Allow levelling up, that gives stat boosts, increased vision range, and a reputation title that grows as you get further
- Adding scent maps for certain enemies to track you
- All item drops come from defeated enemies
- Adding multiple levels to the first cave
- After so many turns on a level, all defeated enemies will resurrect but provide zero Experience Points to force you to keep moving
- Add overworld map that allows you to visit caves and dungeons with different themes / difficulty levels
- Add Literacy skill that allows you to learn by reading / deciphering scrolls
- Add ranged combat

That should be enough for now

**Comment by gcarreno** [comment]
Hey Chris,

WOW, that's a hell of a small list :)

Thanks for all you've done so far and I'm looking forward to test all individual bullet point on that list!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @cyberfilth ,

I think this issue needs to be revisited. From my last play, and it was a tad ago, I died twice while testing, so invincibility is now off the table, hum?

Cheers,
Gus

**Comment by cyberfilth** [comment]
Yep, the player can now die in a couple of different ways with the killer/method of death displayed on the 'game over' screen.
