### ISSUE TITLE
"Access Violation" on calling Inventory right after "Load Game"

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#2]
Hey Chris,

If you press `<I>` on a loaded game you get an `Access Violation`.

The Inventory screen is not shown but the game is still in Inventory screen mode.

Hitting `<ESC>` gets you playing the game again.

But if you hit `<I>` again, it geos as above.

Cheers,
Gus

**Comment by cyberfilth** [comment]
I've only recently added items and I'm still playing around with their data structure. Once I've settled on a format that can accommodate consumables, weapons and armour I'll add them to the save / load function.

**Comment by gcarreno** [comment]
Hey Chris,

Ahhh, so ATM not a bug but a feature, LOL!!

I have to be frank and admit I didn't check if you had code to load Inventory data from saved file. Sorry!

Maybe add a TODO tag to this one to serve as a reminder?

Cheers,
Gus

**Comment by cyberfilth** [comment]
Duly noted. I've added a TODO note in the global_utils unit to remind my quarantine-addled brain in a few days.
I'll close this issue in the meantime.
