### ISSUE TITLE
[Request for Comment] In regards to my promise of tests

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#22]
Hey @cyberfilth,

How would you characterise the stability of your most basic data containers?

Are they stable enough that I can start dishing out some tests?

If you still have fluid ones, just gimme a list of the more solid ones so I can, at least, begin to full fill my promise :wink:

Cheers,
Gus

**Comment by cyberfilth** [comment]
Sorry for the late response, I've been offline for a while and development slowed down.
I've been trying out various implementations of adding multiple levels to the dungeons/caves and fell into a rabbit hole!

Items, weapons, armour and enemies are stable enough for the time being. Variations will be added but the core features will stay the same now. If you still have the time and the inclination, test away! ;-)

**Comment by gcarreno** [comment]
Hey @cyberfilth ,

Yeah, I saw mentions on some commit of levels and even tried to see if you already had a door at least, guess not, LOL!!

Ok, with those in mind I'll start testing.

Cheers,
Gus
