### ISSUE TITLE
I no longer have a Load option on the initial menu

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#25]
Hey @cyberfilth (Chris)

This is more of a question than an issue report...

Have you deprecated loading a map or is it the fact that I haven't used the app in so long that a very old Load file is messing something up?

Cheers,
Gus

**Comment by cyberfilth** [comment]
I forgot to include the version number in the save game data so that'll make it difficult to pinpoint.
If you start a new game and quit does it give you the option to load your last game then?

**Comment by gcarreno** [comment]
Hey @cyberfilth 

> If you start a new game and quit does it give you the option to load your last game then?

I've played the game several times(and died, it's now challenging :D !!) and only on my first run, after correcting the typo did I remember it had a Load option.

After that the option just disappeared.

Cheers,
Gus

PS: Where is the save file again, I forgot?! Thanks!

**Comment by gcarreno** [comment]
Hey @cyberfilth 

Ok, found the file name. It should be `$HOME/.config/.axes.data`.

Somehow that file got deleted and it's not getting recreated.

I'm still looking at your code to see if there's another typo when you save the file. that could be it.

I'm guessing a typo since there is no Access Violation upon exit.

Cheers,
Gus

**Comment by cyberfilth** [comment]
Save files are deleted when your character dies. I'm not sure if you were aware of that.
It's one of the fun / frustrating things about roguelikes, permadeath. 
That's why levels are different every time you play, because you'll die a lot and start again!

**Comment by gcarreno** [comment]
Hey @cyberfilth 

Oky, found the solution to this issue:

You are saving to `$HOME/.axes.data` and `FileExists()` to `$HOME/.config/.axes.data`.

I'm guessing you're forgetting a call to `GetUserDir()` when you're saving the data?

I've copied `$HOME/.axes.data` to `$HOME/.config/.axes.data` and the Load option reappears, so defo a missed call to `GetuserDir()`.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @cyberfilth 

> Save files are deleted when your character dies. I'm not sure if you were aware of that.

I was not aware of that and it does make sense.
That explains why I wasn't finding the file.

None the less, after making the screenshots on issue #26, I found that you're saving it to the wrong place. Comment above explains in more detail.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @cyberfilth 

Ok, first let me apologise for completely wasting your time!!! I'm such an idiot!!!

I'm closing this issue cuz **ALL IS FINE AND WORKING AS IT SHOULD**, and, again, I'm a **COMPLETE IDIOT** and should look at the source before shooting my big mouth!!

I wasn't finding the file cuz, like you said, I died a lot!!

Then I mistakenly assumed `GetUserDir()` would return `$HOME/.config`, another error on my part!!

I've ran the game and quit and found that the intended place you wanted was `$HOME/.axes.data` and when that file in **THAT** location is present all works as it should!!

**AAAAAARGH** Please forgive me for completely wasting your time!!

Cheers,
Gus

**Comment by cyberfilth** [comment]
You didn't waste my time at all!
You've found so many of my dumb mistakes, typos, and failures of logic that I think you can be forgiven for trying to make sense of my spaghetti code in a game genre that you're unfamiliar with! ;-)

**Comment by gcarreno** [comment]
Hey Chris (@cyberfilth)

Thank mate!!! I really enjoy helping you and it's always a pleasure to contribute to a project where the lead guy isn't a dude bro with an overinflated ego.

It's just a pleasure to have fun with this!!!

Cheers,
Gus
