### ISSUE TITLE
Offer of Linux ScreenShots

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#26]
Hey @cyberfilth 

Here are 2 Linux screenshots if you want them.

![cyberfilth-axe-in-game](https://user-images.githubusercontent.com/81799/105497861-58971900-5cb7-11eb-8efe-25f2fc8ba89a.png)
![cyberfilth-axe-main-menu](https://user-images.githubusercontent.com/81799/105497866-59c84600-5cb7-11eb-8cc0-b7eefe6887f3.png)

Cheers,
Gus

**Comment by cyberfilth** [comment]
Screenshot gratefully added, since my Linux laptop is currently between distros
