### ISSUE TITLE
Start state edge case, VERY edge...

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#3]
Hey Chris,

This will probably only happen, lets say, once in a life time **BUT** in one of the times I tested it, a new game gave me 1 tile with 3 objects`*`:

* The player
* A Beer barrel
* A rat

`* this was at the very beginning of the game, right after pressing `<N>` on the initial menu.`

I know, what's the odds, since the map is not that small to stumble on the non randomness of random.

Dunno if you wanna test for this **VERY** edgy corner case, but I thought I should let you know :)

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Chris,

Did you fixed this when you committed this: e3ed92a ?

If so, please close the issue, thanks!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @cyberfilth ,

Is this still something that lingers in your most recent code?

Cheers,
Gus

**Comment by cyberfilth** [comment]
NPC's are no longer spawned on top of the player, I was holding off on closing this whilst the Item generation code was still in flux but at the moment items are only found by breaking open barrels.
