### ISSUE TITLE
Arguments and local variables with same name, is that "legal"?

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#31]
Hey Chris (@cyberfilth)

On your last commit, with the smell unit your `floodfill()` procedure looks like this:

```pascal
procedure floodFill(r, c: smallint);
var
  r, c: smallint;
{...}
```

Are you sure this is not a copy paste error with the `sniff()` procedure?
Which one of the variables are you accessing with a declaration like this?
How does it affect the recursion?
I am so confused right now!! LOL!!

If it is how you intended, just ignore me.

Cheers,
Gus

**Comment by cyberfilth** [comment]
That's definitely a senior moment on my part!
I'll put a fix in place tomorrow, thanks.

**Comment by gcarreno** [comment]
> That's definitely a senior moment on my part!

**ROTFLMAO**

I'm now **VERY** intrigued on how this is allowed by the parser and how it all behaves with recursing.

I need to make a test program to answer all my above questions.

Cheers,
Gus

**Comment by cyberfilth** [comment]
Updated to remove the variable declarations
