### ISSUE TITLE
Circular unit reference in universe.pas

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#32]
Hi Chris(@cyberfilth),

```console
$ lazbuild axe.lpi  # branch DEV-savefile
...
(3104) Compiling universe.pas
Axes-Armour-Ale/universe.pas(10,30) Fatal: (10020) Circular unit reference between universe and cave
Fatal: (1018) Compilation aborted
...
```
Cheers,
Gus

**Comment by cyberfilth** [comment]
Hi Gus,

The changes in the DEV branch won't compile until they're merged back into the main branch.
There's some major refactoring that'll be going on over the next couple of weeks (whenever I get some free time) so I tend to use a DEV branch to commit to until the code is back in some semblance of order.

regards,
Chris

**Comment by gcarreno** [comment]
Hey Chris(@cyberfilth),

So I'm assuming that you're dropping text like it's hot, but not hitting SHIFT+F9 every minute or so?
Cuz I don't see it compiling on your side also...

And this is just a quick fix of swapping a unit from Interface Uses to Implementation Uses, I think.

Cheers,
Gus
