### ISSUE TITLE
Enhancement : Short-cut key to exit game, or at least go back to initial menu.

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#4]
Hey Chris,

Consider your poor testers that have to always close and re-run the app in order to get a new game.

Never the less, it's kinda expected of any game, right? **;-P**

Cheers,
Gus

**Comment by cyberfilth** [comment]
Pressing the ESCAPE key now brings up a prompt that allows you to exit the game or quit to the menu.

**Comment by gcarreno** [comment]
Hey Chris,

Thank you very much, you're the Dude !!

Cheers,
Gus
