### ISSUE TITLE
FR - cp437 output?

### ISSUE THREAD

**Issue by ryanfantus** [cyberfilth/Axes-Armour-Ale#40]
Hello. I was wondering if it would be possible/interesting for you to implement a cp437 code page so I can host this on a telnet BBS? :)

**Comment by cyberfilth** [comment]
It's not something that I've looked into before, but it sounds interesting.
I've got a couple of things on my to-do list, then I'll take a look at if it's possible / how much refactoring it would take.

Thanks for the suggestion!

**Comment by DrDub** [comment]
Free Pascal default Video is cp437. It was ported to unicode recently (see https://www.mail-archive.com/fpc-devel@lists.freepascal.org/msg14512.html). To run in in cp437 the terminal should be set to cp437 and it should work, according to the source code: https://github.com/slibre/freepascal/blob/master/rtl/unix/video.pp
