### ISSUE TITLE
Could you, please, make this like Lazarus's project?

### ISSUE THREAD

**Issue by theavege** [cyberfilth/Axes-Armour-Ale#48]
Could you, please, make this like [Lazarus](https://www.lazarus-ide.org/)'s project?

**Comment by cyberfilth** [comment]
It was originally a Lazarus project, but I ran into some issues with attaching the debugger to the terminal from Lazarus. So I changed it to a plain Pascal project. [There's a write-up of it here.](https://cyberfilth.co.uk/using-the-free-pascal-ide-for-a-week/)
There are also supporting scripts to aid development in the _scripts_ folder.

If you'd like to edit it through Lazarus then there's always the option to change the filename Axes.pas to Axes.lpr, but I'm keeping the source code as plain Pascal to help with the coding, debugging cycle.
