### ISSUE TITLE
Suggestion: Update badges to reflect full FPC and Lazarus versions

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/Axes-Armour-Ale#9]
Hey Chris,

If you look at the combinations of Lazarus and FPC versions running under the Actions, you can put labels like this:

https://img.shields.io/badge/Free%20Pascal-3.0.0~3..0.4-blue.svg : [![Supported FreePascal version: FPC-3.0.0 FPC-3..0.4](https://img.shields.io/badge/Free%20Pascal-3.0.0~3..0.4-blue.svg)](https://github.com/cyberfilth/Axes-Armour-Ale)

https://img.shields.io/badge/Lazarus-1.6.2~2.0.8-blue.svg : [![Supported Lazarus version: Laz-1.6.2 Laz-2.0.8](https://img.shields.io/badge/Lazarus-1.6.2~2.0.8-blue.svg)](https://github.com/cyberfilth/Axes-Armour-Ale)

Cheers,
Gus

**Comment by cyberfilth** [comment]
Done. I've updated the badges (linked to the .svg images as shields.io servers are not always reliable)

**Comment by gcarreno** [comment]
Hey Chris,

Yeah, I noticed you did that for the previous one. Good call.

Cheers,
Gus
